### ISSUE TITLE
Problem with swagger.json

### ISSUE THREAD

**Issue by luigi-asprino** [spice-h2020/linked-data-hub-env-docker#3]
Hi,

I've put the ``swagger-config-main.json`` file (available at ``http://spice-apif.local/swagger-config-main.json``) describing the APIFactory interface on the [Swagger Editor](https://editor.swagger.io/) available online in order to automatically generate a client for the APIs.
I got an error that says that getDocuments operationId cannot be repeated.
Basically, there are 2 operations  with the same ID:
- the GET  on path ``/browse/{dataset-uuid}``
- the GET on path ``/object/{dataset-uuid}``
This seems to be wrong for Swagger.

**Comment by JaseMK** [comment]
Fixed on the main API Factory repository:
https://github.com/mkdf/api-factory/commit/29df130dacf53caf3c8bb08e1668c21b711f2fae
